name: Build iOS IPA

on:
  push:
    branches: [ master ]

jobs:
  build-ios:
    runs-on: macos-13

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: beta
        flutter-version: '2.13.0-0.1.pre' # 根据你的项目调整版本

    - name: Install Dependecies
      run: |
        flutter pub get
        
    - name: Build iOS (Debug)
      run: |
        flutter build ios --debug --no-codesign
